// For Auth
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// For Lists
export const LISTS_START = 'LIST_START'
export const LISTS_ERROR = 'LIST_ERROR'
export const LISTS_RETRIEVE = 'LIST_RETRIEVE'
export const LISTS_SET_CURRENT = 'LIST_SET_CURRENT'
export const LISTS_CLEAR = 'LISTS_CLEAR'
export const LISTS_ADD_NEW = 'LISTS_ADD_NEW'
export const LISTS_UPDATE_PROBLEMS = 'LISTS_UPDATE_PROBLEMS'

// For Problems
export const PROBLEMS_START = 'PROBLEMS_START'
export const PROBLEMS_ERROR = 'PROBLEMS_ERROR'
export const PROBLEMS_RETRIEVE = 'PROBLEMS_RETRIEVE'
export const PROBLEMS_SET_CURRENT = 'PROBLEMS_SET_CURRENT'
export const PROBLEMS_SET_TON = 'PROBLEMS_SET_TON'
export const PROBLEMS_CLEAR = 'PROBLEMS_CLEAR'